language: node_js
node_js:
  - 12
services:
  - docker
cache:
  directories:
    - node_modules
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed baohuynhgia/udagram-api-feed:v1
  - docker tag udagram-api-user baohuynhgia/udagram-api-user:v1
  - docker tag udagram-frontend baohuynhgia/udagram-frontend:v1
  - docker tag udagram-reverseproxy baohuynhgia/udagram-reverseproxy:v1
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push baohuynhgia/udagram-api-feed:v1
  - docker push baohuynhgia/udagram-api-user:v1
  - docker push baohuynhgia/udagram-frontend:v1
  - docker push baohuynhgia/udagram-reverseproxy:v1
  #trigger v2